/** Rich SEO descriptions per event slug. Used on individual event pages. */
export const eventContent: Record<string, { intro: string; details: string; ideal: string; includes: string[]; groupSize: string; price: string }> = {
  // ── Bridal ──
  "bridal-hair-and-makeup": {
    intro: "Your wedding day deserves flawless hair and makeup — and zero stress getting there. Our bridal team arrives at your hotel, home, or venue with everything needed to make you camera-ready from first look to last dance.",
    details: "Our licensed bridal stylists and makeup artists specialize in long-lasting, photograph-ready looks designed to hold up through tears, hugs, dancing, and every candid moment in between. We work with you during your trial run to lock in the perfect look, then recreate it on the big day with precision. We bring professional lighting, mirrors, all tools, products, and backup supplies — you just sit back and enjoy your morning.",
    ideal: "For brides who want the full salon experience without the salon. Get glammed up surrounded by your closest people, in your own space, on your timeline.",
    includes: ["Bridal hair styling (updo, half-up, loose waves, etc.)", "Full glam makeup with setting spray", "Lash application", "Touch-up kit for the day", "Professional lighting & mirrors"],
    groupSize: "1 bride (add bridesmaids separately)",
    price: "$350",
  },
  "bridal-party-hair-and-makeup": {
    intro: "Get the entire bridal party glammed up together — bridesmaids, mother of the bride, mother of the groom, flower girls, and anyone else who wants in. Multiple stylists arrive simultaneously so everyone is ready on time.",
    details: "We send a full team of licensed hair stylists and makeup artists who work in parallel, so a party of 8 doesn't take 8 hours. Each person gets a personalized consultation, professional styling, and a look that complements the wedding aesthetic. We coordinate with photographers on timing and can work around any schedule. We bring all tools, products, capes, mirrors, and setup — your space stays clean and drama-free.",
    ideal: "Perfect for wedding mornings, rehearsal dinners, and engagement parties. The whole crew gets ready together — no one has to drive to a salon at 5am.",
    includes: ["Hair styling per person", "Full makeup per person", "Lash application available", "Coordinated scheduling with photographer", "Multi-stylist team for efficiency"],
    groupSize: "3-15+ people",
    price: "$200/person",
  },
  "bridal-trial-run": {
    intro: "A preview session before your big day to test drive your bridal hair and makeup look. We come to you, try multiple options, take photos, and lock in exactly what you want so there are zero surprises on the wedding day.",
    details: "Your trial run is a full 90-minute session where your stylist and makeup artist work with you to find the perfect combination of hair and makeup. Bring inspiration photos, your veil or headpiece, and any accessories you'll wear on the day. We'll try multiple looks, photograph each one, and finalize every detail — products, shades, placement, hold level — so the wedding day is seamless.",
    ideal: "Essential for any bride who wants peace of mind. Typically booked 4-8 weeks before the wedding. We recommend doing the trial in the same space you'll get ready on the actual day.",
    includes: ["90-minute session", "Multiple look trials", "Photo documentation of final look", "Product & shade notes for wedding day", "Consultation on accessories & veil styling"],
    groupSize: "1 person",
    price: "$250",
  },
  "engagement-boudoir-shoot-glam": {
    intro: "Photo-ready hair and makeup for engagement sessions, boudoir shoots, and couple's photography. We make sure you look effortlessly stunning in every frame — whether it's Central Park, a rooftop, or a studio.",
    details: "Our stylists create looks that photograph beautifully in any lighting and setting. We consider your outfit changes, locations, and the overall vibe of your shoot to design hair and makeup that feels authentic to you but elevated for the camera. We can stay on set for touch-ups between looks or outfit changes.",
    ideal: "For engagement photos, boudoir sessions, anniversary shoots, proposal setups, and any photo-heavy milestone moment.",
    includes: ["Hair styling", "Full makeup application", "Setting spray for longevity", "Touch-ups between outfit changes (if booked)", "Consultation on shoot-appropriate looks"],
    groupSize: "1-2 people",
    price: "$275",
  },

  // ── Parties & Celebrations ──
  "birthday-glam-party": {
    intro: "Turn any birthday into a full-blown glam party. We bring a team of stylists for blowouts, makeup, manicures, and more — so the birthday crew looks and feels amazing before hitting the town.",
    details: "Our birthday packages are fully customizable. Pick and choose services — blowouts, gel manis, full glam makeup, lash applications, updos, braids — and we build a custom schedule so everyone gets pampered. We work in parallel with multiple pros to keep things moving. Great for apartments, hotel suites, Airbnbs, or any space where you want the party to start with pampering.",
    ideal: "Perfect for milestone birthdays, surprise parties, or any celebration where looking amazing is part of the plan.",
    includes: ["Customizable service menu", "Multiple stylists working simultaneously", "All tools & products provided", "Music-friendly setup", "Group coordination"],
    groupSize: "4-20+ people",
    price: "$150/person",
  },
  "bachelorette-pampering": {
    intro: "The ultimate bachelorette party starts with pampering. We bring blowouts, nails, makeup, and spa vibes directly to your hotel, Airbnb, or apartment — so the whole crew is ready to celebrate.",
    details: "Our bachelorette packages combine beauty services with a spa-like atmosphere. We can set up mini stations for manis, blowouts, and makeup so everyone rotates through. Add champagne (you supply) and good music and you've got the perfect pre-night-out experience. We customize the services to fit your group size, timeline, and vibe — whether it's laid-back pampering or full glam transformation.",
    ideal: "Ideal for the night before, the morning of, or any point during a bachelorette weekend when the crew needs to look their best.",
    includes: ["Blowout or styling per person", "Gel manicure per person", "Makeup application available", "Flexible scheduling", "Multi-stylist team"],
    groupSize: "4-15 people",
    price: "$175/person",
  },
  "sweet-16-quinceanera-glam": {
    intro: "Make the guest of honor shine on their special day. Professional hair, makeup, and nail services for the birthday girl and her closest friends — delivered to your home or venue.",
    details: "We specialize in age-appropriate glam that makes teens feel confident and beautiful. Our stylists work with the guest of honor to create a standout look, then glam up friends and family members as well. We coordinate with event timelines and photographers, and we bring all professional-grade tools and products. Parents can join in too — everyone deserves to feel special.",
    ideal: "Perfect for Sweet 16 parties, quinceañeras, bat mitzvahs, and any coming-of-age celebration.",
    includes: ["Guest of honor styling & makeup", "Hair & makeup for guests", "Age-appropriate product selection", "Timeline coordination", "All tools & products"],
    groupSize: "5-20+ people",
    price: "$125/person",
  },
  "prom-prep-party": {
    intro: "Get the whole prom group ready together — updos, curls, glam makeup, nails, and all the finishing touches. We come to you so nobody has to worry about salon appointments on the biggest night of the year.",
    details: "Our prom packages are designed for groups who want to get ready together and make it part of the experience. Multiple stylists arrive and work simultaneously on hair, makeup, and nails. We create looks that are photo-ready, dance-proof, and designed to last all night. We work with all hair types and textures, and we're experienced with teen-appropriate glam that parents will love too.",
    ideal: "For friend groups who want the getting-ready process to be as memorable as prom itself. Book early — prom season fills up fast.",
    includes: ["Updo or formal styling", "Full makeup application", "Setting spray for all-night hold", "Nail services available", "Group scheduling & coordination"],
    groupSize: "3-10 people",
    price: "$150/person",
  },
  "girls-night-in": {
    intro: "Skip the overpriced bar and bring the glam to your living room. Manis, pedis, blowouts, and good vibes — our team turns any night in into a full-service pampering party.",
    details: "Girls' Night In packages are our most popular group booking. We customize the menu to your crew's preferences — some groups go all-in on nails, others want blowouts and facials, and some want the full works. We bring spa-quality products, professional tools, and a relaxed vibe. You bring the wine and the playlist. Works great in apartments, homes, hotel suites, and Airbnbs anywhere in NYC.",
    ideal: "Ideal for friend reunions, weekend wind-downs, holiday gatherings, or just because you and your crew deserve it.",
    includes: ["Customizable service menu", "Gel manicures & pedicures", "Blowout styling", "Express facials available", "Relaxed group setup"],
    groupSize: "4-12 people",
    price: "$125/person",
  },
  "spa-day-at-home": {
    intro: "Transform your home into a luxury spa. Facials, nails, hair, and relaxation — our team sets up a full spa experience in your space, no travel required.",
    details: "Our Spa Day at Home brings the full wellness experience to your living room, bedroom, or any space you choose. We set up professional treatment stations and work in parallel with multiple specialists — one person gets a facial while another gets a mani/pedi. We use premium spa-grade products for every treatment. It's a full spa day without the Uber, the parking, or the awkward locker room.",
    ideal: "Perfect for birthdays, bridal parties, self-care days, or treating your mom, sister, or best friend to something special.",
    includes: ["Express or deep facials", "Manicures & pedicures", "Hair styling", "Scalp treatments available", "All spa-grade products"],
    groupSize: "2-10 people",
    price: "$175/person",
  },
  "baby-shower-pampering": {
    intro: "Pamper the mama-to-be and her guests with mobile beauty services at the baby shower. Nails, mini facials, blowouts, and feel-good vibes — we bring everything to your venue.",
    details: "Our baby shower packages are designed to be gentle, relaxing, and fun. The mama-to-be gets the VIP treatment with her choice of services, and guests rotate through pampering stations. We use pregnancy-safe products and gentle techniques, and our team is experienced working around baby bumps and comfort needs. We handle all setup and cleanup so the host can focus on celebrating.",
    ideal: "Perfect for both the shower itself or a pre-shower pampering session with the inner circle. Works beautifully at homes, restaurants with private rooms, or event spaces.",
    includes: ["Priority service for mama-to-be", "Pregnancy-safe products", "Manicure & pedicure stations", "Express facials", "Gentle hair styling"],
    groupSize: "6-20+ people",
    price: "$100/person",
  },

  // ── Corporate & Professional ──
  "office-wellness-day": {
    intro: "Boost team morale with on-site beauty and wellness services. We set up professional stations at your office for manicures, chair massages, brow bars, and more — employees just walk up and get pampered.",
    details: "Our corporate wellness packages are designed for minimal disruption and maximum impact. We set up one or more stations in a conference room, lounge, or any available space. Employees sign up for 15-30 minute service slots throughout the day. Popular choices include express manicures, brow cleanups, hand massages, and mini facials. We bring everything — tables, chairs, tools, products, and sanitization supplies. Perfect for Employee Appreciation Day, Women's History Month, Mental Health Day, or just a regular Tuesday that needs a boost.",
    ideal: "For companies of any size who want to show their team some love. We've served startups, Fortune 500s, law firms, hospitals, and everything in between.",
    includes: ["On-site setup & breakdown", "Express service stations", "Professional sanitization", "Employee scheduling system", "Customizable service menu"],
    groupSize: "15-200+ employees",
    price: "$75/person",
  },
  "headshot-photo-shoot-styling": {
    intro: "Professional hair and makeup for team headshots, company photo shoots, and corporate portraits. We make sure every person on your team looks polished, confident, and camera-ready.",
    details: "Our corporate styling team works alongside your photographer to ensure every person gets a look that's professional, flattering, and brand-appropriate. We handle quick touch-ups between shots, style multiple people efficiently, and keep things moving so the photo session stays on schedule. We work with all hair types, skin tones, and personal styles — the goal is always to make each person look like the best version of themselves.",
    ideal: "Essential for website refreshes, LinkedIn updates, annual reports, marketing campaigns, and any time your team needs to look their best on camera.",
    includes: ["Hair styling per person", "Natural makeup application", "Touch-ups between shots", "On-set coordination with photographer", "Express turnaround available"],
    groupSize: "5-50+ people",
    price: "$125/person",
  },
  "conference-touch-up-station": {
    intro: "Quick-service beauty stations at your conference, trade show, or corporate event. Attendees stop by for a touch-up, blowout refresh, or express mani — a memorable activation that keeps them at your booth.",
    details: "We set up branded or neutral beauty stations wherever you need them — booth, lounge area, VIP section, or registration area. Services are designed to take 10-20 minutes so attendees can pop in, get pampered, and get back to the event. Popular options include express blowout touch-ups, hand massages with branded lotion, quick manicures, brow cleanups, and lip touch-up stations. We can customize signage and product branding for sponsor activations.",
    ideal: "High-impact experiential marketing for conferences, trade shows, product launches, and networking events. Drives foot traffic and creates buzz.",
    includes: ["Custom station setup", "Quick-service beauty options", "Branded experience available", "Flexible staffing by event size", "All supplies & cleanup"],
    groupSize: "50-500+ attendees",
    price: "Custom quote",
  },
  "employee-appreciation-glam": {
    intro: "Reward your team with a pampering experience they'll actually remember. We bring mobile beauty services to your office or event space for a day of appreciation and self-care.",
    details: "Employee appreciation should feel special — not like another email. We set up full-service beauty stations where your team can choose from manicures, mini facials, blowouts, brow cleanups, and more. Services run in 15-30 minute slots so work doesn't stop completely, and employees sign up for the times that work for them. We handle all setup, scheduling, and cleanup. You just take the credit.",
    ideal: "For end-of-quarter celebrations, holiday parties, team milestones, or anytime you want to say 'thank you' in a way that actually lands.",
    includes: ["On-site setup & breakdown", "Multi-service stations", "Flexible scheduling", "Thank-you cards / branded elements available", "All products & tools"],
    groupSize: "10-100+ employees",
    price: "$85/person",
  },

  // ── Film / Photo / Content ──
  "on-set-hair-and-makeup": {
    intro: "Production-grade hair and makeup for film, TV, music videos, and commercial shoots. Our on-set team is experienced, efficient, and ready to work within any production schedule.",
    details: "Our on-set stylists and makeup artists understand the demands of production — early call times, quick changes, continuity, and working under pressure. We provide professional looks for any genre, era, or character requirement. We bring professional kits stocked with everything from natural beauty to full SFX-adjacent glam. We're experienced with HD, 4K, and high-contrast lighting requirements. We can provide one artist or a full team depending on your cast size and production needs.",
    ideal: "For independent films, commercials, music videos, TV segments, live broadcasts, and any production that needs reliable, professional hair and makeup.",
    includes: ["On-set hair & makeup artist(s)", "Full professional kit", "Continuity photos & notes", "Touch-ups throughout shoot", "Flexible call times"],
    groupSize: "1-20+ talent",
    price: "$500/day",
  },
  "content-creator-glam": {
    intro: "Look amazing on camera without spending 3 hours on your own hair and makeup. Our content creator packages give influencers, YouTubers, podcasters, and TikTokers a professional, camera-ready look fast.",
    details: "We specialize in looks that pop on camera — whether you're shooting in natural light, a ring light, or a full studio setup. Our stylists understand color theory, camera angles, and how different platforms affect how makeup reads. We work quickly (most creator looks take 30-45 minutes) and can pivot between multiple looks for different content pieces. Regulars can lock in recurring weekly or monthly bookings at a preferred rate.",
    ideal: "For influencers, YouTubers, podcasters, live streamers, and anyone creating content who wants to look polished and professional without DIY-ing it.",
    includes: ["Camera-ready hair styling", "Professional makeup for content", "Quick look changes available", "Platform-optimized technique", "Recurring booking discounts"],
    groupSize: "1-5 people",
    price: "$200",
  },
  "lookbook-editorial-styling": {
    intro: "High-fashion editorial hair and makeup for lookbooks, fashion shoots, catalogs, and brand campaigns. Our editorial team brings the creativity and precision that fashion-forward visuals demand.",
    details: "Our editorial stylists and makeup artists work with photographers, creative directors, and designers to bring creative visions to life. We handle everything from natural beauty to avant-garde editorial looks, and we're experienced with diverse models, skin tones, and hair textures. We bring full professional kits with high-end products and can provide multiple artists for larger shoots with multiple models or look changes.",
    ideal: "For fashion brands, designers, magazines, e-commerce, and any creative project that requires editorial-level hair and makeup.",
    includes: ["Editorial hair styling", "High-fashion makeup", "Multiple look changes", "Creative direction collaboration", "Full professional kit"],
    groupSize: "1-10+ models",
    price: "$400/day",
  },
  "red-carpet-press-prep": {
    intro: "Red carpet ready in your hotel room, dressing room, or home. We prepare celebrities, public figures, and VIPs for press events, premieres, galas, and award shows with flawless, camera-ready glam.",
    details: "Our red carpet team understands the stakes — every angle will be photographed, every detail scrutinized. We create looks designed to shine under flash photography and stage lighting while still looking natural and effortless up close. We coordinate with stylists and publicists on overall look direction, and we stay on standby for last-minute touch-ups before you step out. Discretion and professionalism are guaranteed.",
    ideal: "For celebrities, public figures, executives, influencers, and anyone walking a red carpet, attending a gala, or appearing on camera at a high-profile event.",
    includes: ["Full glam hair & makeup", "Flash-photography-optimized makeup", "Coordination with wardrobe stylist", "On-call touch-ups", "Premium products & tools"],
    groupSize: "1-3 people",
    price: "$500",
  },

  // ── Community & Specialty ──
  "senior-home-salon-day": {
    intro: "Bring the salon experience to assisted living, nursing homes, and senior communities. Our gentle, experienced stylists provide haircuts, styling, manicures, and hand massages that brighten everyone's day.",
    details: "Our senior salon services are designed with care, patience, and respect. We work with residents individually, taking the time to listen to what they want and make them feel special. Popular services include wash and sets, blowouts, gentle trims, manicures, and hand massages. We understand mobility limitations and work comfortably with wheelchairs, walkers, and limited range of motion. We bring all tools and products and clean up after ourselves.",
    ideal: "For nursing homes, assisted living facilities, senior centers, and retirement communities. A wonderful addition to activity calendars and holiday celebrations.",
    includes: ["Gentle haircuts & styling", "Manicures & hand care", "Wash & set", "Patient, one-on-one attention", "All tools & cleanup"],
    groupSize: "5-30+ residents",
    price: "$50/person",
  },
  "hospital-recovery-pampering": {
    intro: "A little pampering goes a long way during tough times. We bring gentle beauty services to hospital patients, post-surgery recovery rooms, and anyone healing at home who could use a boost.",
    details: "Our hospital and recovery pampering services are gentle, compassionate, and designed to make someone feel human again. A fresh wash and style, a careful manicure, or a gentle hand massage can transform a hard day. We use hypoallergenic, fragrance-free products when needed and work within any medical restrictions. We coordinate with nursing staff or caregivers to ensure every service is safe and comfortable.",
    ideal: "For patients recovering from surgery, long hospital stays, cancer treatment, or anyone going through a tough time who deserves to feel cared for.",
    includes: ["Gentle hair wash & styling", "Careful manicure", "Hand & arm massage", "Hypoallergenic products available", "Coordination with medical staff"],
    groupSize: "1-10 people",
    price: "$75/person",
  },
  "shelter-nonprofit-glam-event": {
    intro: "Confidence-boosting beauty services for shelters, nonprofits, and community organizations. We volunteer our time and talent to help people look and feel their best during job interviews, milestones, and fresh starts.",
    details: "We partner with shelters, workforce development programs, domestic violence organizations, and community nonprofits to provide professional haircuts, styling, manicures, and makeup application. These events are about more than beauty — they're about dignity, confidence, and feeling ready to take on the next chapter. We bring a full team and all supplies at reduced or donated rates, and we treat every person with the same care and attention as our highest-paying clients.",
    ideal: "For nonprofit organizations, shelters, community centers, workforce programs, and any group working to lift people up. Contact us about donated or reduced-rate services.",
    includes: ["Haircuts & styling", "Manicures", "Makeup application", "Full team of volunteers", "All supplies donated"],
    groupSize: "10-50+ people",
    price: "Donated / reduced rate",
  },
  "back-to-school-kids-haircuts": {
    intro: "Fresh cuts for the first day of school — delivered to your home, community center, or school. We make back-to-school haircuts fun, fast, and stress-free for parents and kids alike.",
    details: "Our back-to-school packages are designed for families and communities who want to start the school year right. We handle kids of all ages and hair types — from toddler trims to teen fades, braids, and styles. We're patient with wiggly kids, fast with teens who have places to be, and thorough with everyone. For community events, we set up multiple stations and process kids efficiently while keeping the vibe fun and welcoming.",
    ideal: "Perfect for families, community organizations, schools, and churches running back-to-school events. We also do individual family bookings at home.",
    includes: ["Kids' haircuts (all ages)", "Braids & styles available", "Multiple barber/stylist setup for events", "Fun, kid-friendly experience", "All tools & cleanup"],
    groupSize: "1-50+ kids",
    price: "$40/child",
  },
};
