/** Rich SEO descriptions per service slug. Used on individual service pages. */
export const serviceContent: Record<string, { intro: string; details: string; ideal: string; includes: string[]; duration: string; price: string }> = {
  // ── Women's Hair ──
  "blowouts-and-styling": {
    intro: "A salon-quality blowout delivered to your door. Our licensed hairstylists bring professional-grade tools and premium products to give you bouncy, voluminous, camera-ready hair without leaving your apartment.",
    details: "Whether you need a sleek straight blowout for work, loose waves for date night, or voluminous curls for a special event, our stylists customize every blowout to your hair type, texture, and desired look. We work with all hair types \u2014 fine, thick, curly, coily, and everything in between. Our pros use professional dryers, round brushes, flat irons, and curling wands, plus heat protectant and finishing products to keep your style lasting all day (or all night).",
    ideal: "Perfect for before work, date nights, girls\u2019 night out, photo shoots, events, or anytime you want to feel like you just walked out of a top Manhattan salon \u2014 except you never left your couch.",
    includes: ["Shampoo & conditioning", "Professional blow dry", "Styling (straight, waves, or curls)", "Heat protection", "Finishing products"],
    duration: "45\u201360 min",
    price: "$99",
  },
  "haircuts-and-trims": {
    intro: "Precision haircuts and trims delivered to your door by licensed NYC hairstylists. From a quick maintenance trim to a full transformation, we cut to your face shape, lifestyle, and personal style.",
    details: "Our stylists specialize in everything from blunt cuts and long layers to pixie cuts, bobs, shags, curtain bangs, and textured crops. We consult with you before every cut to understand exactly what you\u2019re looking for \u2014 bring a photo, describe a vibe, or let your stylist recommend based on your face shape and hair texture. Every cut includes shampoo, conditioning, and a finishing style.",
    ideal: "Ideal for anyone who dreads the salon commute or can\u2019t find time between work, kids, and life to sit in a chair for two hours. We come to you \u2014 morning, evening, or weekend.",
    includes: ["Consultation", "Shampoo & conditioning", "Precision cut or trim", "Blow dry & style"],
    duration: "45\u201375 min",
    price: "$120",
  },
  "single-process-color": {
    intro: "Full hair color, root touch-ups, and gray coverage delivered to your home by licensed colorists. We bring professional-grade color products and all the tools needed for a flawless result.",
    details: "Our colorists work with top professional color lines to deliver rich, even, long-lasting results. Whether you want to go darker, cover grays, refresh your existing shade, or try something completely new, we handle it all. We protect your space with drop cloths and professional capes, and we\u2019ll need access to a sink for rinsing. Every color service includes a consultation to find your perfect shade.",
    ideal: "Great for busy professionals, new moms, or anyone who wants salon-quality color without the 3-hour salon visit. We handle everything \u2014 you just relax.",
    includes: ["Color consultation", "Full application or root touch-up", "Processing time", "Rinse, condition & style", "Space protection setup"],
    duration: "90\u2013120 min",
    price: "$175",
  },
  "double-process-color": {
    intro: "Dramatic color transformations delivered to your door \u2014 bleach and tone for platinum, fashion colors, and bold looks. Our licensed colorists specialize in the precision and care that double-process requires.",
    details: "Double-process color means we lighten your hair first, then apply a toner or color on top for the final shade. This is how you get platinum blonde, icy tones, pastels, vivid fashion colors, and dramatic transformations. It requires an experienced hand and professional products \u2014 our colorists have years of experience and use bond-protecting treatments to keep your hair healthy throughout the process.",
    ideal: "Perfect for anyone ready for a bold change \u2014 going platinum, trying a fashion color, or correcting previous color work. Not a DIY job \u2014 this is why you hire a pro.",
    includes: ["Color consultation", "Lightening/bleach application", "Toner application", "Bond treatment", "Rinse, deep condition & style"],
    duration: "2\u20133 hours",
    price: "$275",
  },
  "highlights-balayage-ombre": {
    intro: "Highlights, balayage, and ombre coloring delivered to your home by licensed NYC colorists. Add dimension, depth, and sun-kissed warmth without stepping foot in a salon.",
    details: "Our colorists are trained in foil highlights, balayage (hand-painted), ombre, sombre, babylights, and money pieces. We customize the placement, tone, and intensity to complement your skin tone, natural color, and lifestyle. Whether you want subtle, natural-looking dimension or bold, high-contrast highlights, we deliver salon-level results in your living room.",
    ideal: "Ideal for anyone who wants low-maintenance color that grows out beautifully. Balayage and ombre are perfect for busy New Yorkers who want to look great between appointments.",
    includes: ["Color consultation", "Highlight/balayage application", "Processing & toning", "Rinse, condition & style", "Space protection"],
    duration: "2\u20133 hours",
    price: "$250",
  },
  "deep-conditioning-treatment": {
    intro: "Restore moisture, shine, and strength with a professional deep conditioning treatment delivered to your door. Our stylists use salon-grade masks and treatments tailored to your hair\u2019s needs.",
    details: "Whether your hair is dry, damaged, color-treated, heat-stressed, or just needs a boost, our deep conditioning treatments penetrate the hair shaft to restore elasticity, smooth frizz, and add brilliant shine. We use professional-grade hydrating masks, protein treatments, and bond builders depending on what your hair needs. Treatment is applied after a thorough shampoo and often paired with gentle heat for maximum absorption.",
    ideal: "Perfect as a standalone treatment or add-on to any hair service. Great for color-treated hair, natural hair, or anyone dealing with NYC\u2019s winter dryness or summer humidity.",
    includes: ["Hair assessment", "Shampoo", "Deep conditioning mask application", "Heat processing", "Rinse & style"],
    duration: "30\u201345 min",
    price: "$85",
  },
  "silk-press": {
    intro: "A flawless silk press on natural hair, delivered to your door by stylists who specialize in textured hair. Sleek, bouncy, silky-straight results with zero heat damage.",
    details: "A silk press is the art of straightening natural hair using a blow dryer and flat iron without chemical relaxers. Our stylists specialize in working with type 3 and type 4 hair textures, using heat protectant, professional flat irons with adjustable temperature, and finishing serums to achieve that glossy, swinging, silk-like finish that lasts until your next wash day. We protect every strand.",
    ideal: "Perfect for natural hair queens who want a temporary straight style for an event, a new look, or just because. No chemicals, no permanence \u2014 just gorgeous, silky hair.",
    includes: ["Shampoo & conditioning", "Blow dry & detangle", "Flat iron silk press", "Heat protectant throughout", "Finishing serum & style"],
    duration: "90\u2013120 min",
    price: "$150",
  },
  "braids-and-protective-styles": {
    intro: "Box braids, cornrows, twists, locs, passion twists, knotless braids, and more \u2014 delivered to your door by braiders who specialize in protective styling for natural hair.",
    details: "Protective styles are about more than looks \u2014 they\u2019re about keeping your hair healthy, reducing manipulation, and retaining length. Our braiders are skilled in box braids (all sizes), knotless braids, cornrows, Ghana braids, feed-in braids, Senegalese twists, passion twists, Marley twists, faux locs, crochet styles, and more. We bring all necessary hair extensions and accessories \u2014 just tell us what you want.",
    ideal: "Great for anyone who wants a low-maintenance style that lasts 4\u20138 weeks. Perfect before vacation, during transitioning, or as a go-to protective style between wash days.",
    includes: ["Style consultation", "Detangling & prep", "Extension hair (if needed)", "Braiding/twisting", "Edge control & finishing"],
    duration: "3\u20138 hours (varies by style)",
    price: "$150\u2013$400",
  },
  "extensions": {
    intro: "Professional hair extension installation and removal delivered to your home. Clip-ins, tape-ins, sew-ins, micro-links, and more \u2014 by licensed stylists who specialize in extensions.",
    details: "Whether you want length, volume, or both, our extension specialists work with all methods: clip-in application and blending, tape-in installation, sew-in (weave) installation with braided base, micro-link/bead installation, and removal of any method. We also offer blending cuts and color-matching to ensure your extensions look completely natural. We work with virgin hair, synthetic, and heat-friendly options.",
    ideal: "Perfect for weddings, events, or everyday glam. Also great for anyone experiencing thinning who wants to add volume and confidence.",
    includes: ["Consultation & color matching", "Installation or removal", "Blending cut & style", "Care instructions"],
    duration: "1\u20133 hours",
    price: "$200\u2013$500",
  },
  "updo-and-formal-styling": {
    intro: "Elegant updos and formal hairstyling for weddings, galas, proms, and special events \u2014 delivered to your door by licensed event hairstylists.",
    details: "From classic chignons and French twists to romantic loose updos, braided crowns, and modern textured styles, our formal hair specialists create looks that photograph beautifully and hold all day (or all night). We work with your natural hair or extensions, and we bring all the pins, clips, and products needed. Every updo includes a consultation to discuss your outfit, venue, and desired vibe.",
    ideal: "Essential for brides, bridesmaids, prom, galas, holiday parties, and any event where you want to look absolutely stunning.",
    includes: ["Style consultation", "Shampoo & prep", "Updo or formal style", "Pins, accessories & finishing spray", "Touch-up tips"],
    duration: "60\u201390 min",
    price: "$150",
  },

  // ── Women's Nails ──
  "classic-manicure": {
    intro: "A clean, classic manicure delivered to your door. Shape, buff, cuticle care, and your choice of polish \u2014 performed by a licensed nail technician with their own portable station.",
    details: "Our classic manicure includes nail shaping, cuticle pushing and trimming, hand exfoliation, a brief hand massage, and application of your chosen polish color. We bring a full range of OPI, Essie, and Zoya polishes, plus base coat and top coat for a long-lasting finish. Everything is sanitized between clients with hospital-grade protocols.",
    ideal: "Quick, affordable, and perfect for maintenance between gel sets, or for anyone who prefers a natural, non-gel finish.",
    includes: ["Nail shaping & filing", "Cuticle care", "Hand exfoliation & massage", "Polish application", "Top coat"],
    duration: "30\u201340 min",
    price: "$45",
  },
  "gel-manicure": {
    intro: "Chip-free, glossy gel nails delivered to your door. Our licensed nail techs bring professional UV/LED lamps and premium gel polish for a manicure that lasts 2\u20133 weeks.",
    details: "Gel manicures cure under UV or LED light for a hard, chip-resistant finish that stays glossy for weeks. Our techs use premium gel polishes (OPI GelColor, CND Shellac, Gelish) and bring their own portable lamp. Service includes full nail prep, cuticle care, and two coats of color plus top coat. Gel removal from a previous set is available as an add-on.",
    ideal: "The go-to for busy New Yorkers who want long-lasting nails without constant maintenance. Perfect before vacations, events, or just treating yourself.",
    includes: ["Nail shaping & filing", "Cuticle care", "Gel base coat", "Two coats gel color", "Gel top coat & cure"],
    duration: "45\u201360 min",
    price: "$65",
  },
  "classic-pedicure": {
    intro: "A relaxing pedicure delivered to your home \u2014 soak, scrub, massage, and polish. Our nail techs bring a portable foot bath and all supplies needed for happy, polished feet.",
    details: "Our classic pedicure includes a warm foot soak, callus removal, nail trimming and shaping, cuticle care, foot scrub exfoliation, a relaxing foot and calf massage, and polish application. We bring a portable foot basin, towels, and all tools \u2014 everything is sanitized between clients.",
    ideal: "Perfect for summer sandal season, pre-vacation prep, or anytime your feet need some love. Pair it with a manicure for the full experience.",
    includes: ["Foot soak", "Callus removal", "Nail shaping & cuticle care", "Exfoliation & massage", "Polish application"],
    duration: "45\u201360 min",
    price: "$75",
  },
  "gel-pedicure": {
    intro: "Long-lasting gel pedicure delivered to your door. Soak, scrub, massage, and chip-free gel polish that keeps your toes perfect for weeks.",
    details: "All the pampering of a classic pedicure with the durability of gel. Our techs bring portable foot baths, UV/LED lamps, and premium gel polishes. The gel finish resists chipping and peeling, making it perfect for anyone who wants flawless toes without frequent touch-ups.",
    ideal: "Ideal for vacations, summer, events, or anyone who wants a long-lasting pedicure that actually lasts.",
    includes: ["Foot soak & callus removal", "Nail shaping & cuticle care", "Exfoliation & massage", "Gel polish application & cure"],
    duration: "60\u201375 min",
    price: "$85",
  },
  "nail-art": {
    intro: "Custom nail art and hand-painted designs delivered to your door. From minimalist lines to elaborate 3D art, our nail artists bring your vision to life.",
    details: "Our nail artists specialize in freehand designs, geometric patterns, French tips with a twist, ombre, chrome, marble, florals, abstract art, and character designs. Bring a Pinterest board or describe what you want \u2014 we\u2019ll make it happen. Nail art is typically done over gel or acrylic for longevity.",
    ideal: "Perfect for special occasions, matching your outfit, expressing your personality, or just because life\u2019s too short for boring nails.",
    includes: ["Design consultation", "Nail prep & base", "Custom hand-painted art", "Top coat & seal", "Aftercare instructions"],
    duration: "60\u201390 min",
    price: "$85+",
  },
  "acrylic-press-on": {
    intro: "Professional acrylic nail sets and press-on applications delivered to your home. Full sets, fills, and your choice of shape \u2014 coffin, stiletto, almond, square, and more.",
    details: "Our licensed nail techs offer full acrylic sets, acrylic fills, and professional press-on application with customization. Choose your length, shape, and finish \u2014 natural, French, ombre, or custom color. We bring all acrylic products, forms, and tools. Removal of previous sets available as an add-on.",
    ideal: "Great for anyone who wants length and strength. Perfect for events, vacations, or a regular set you maintain with fills every 2\u20133 weeks.",
    includes: ["Shape & length consultation", "Nail prep", "Acrylic application or press-on fit", "Shaping & filing", "Polish or gel finish"],
    duration: "60\u201390 min",
    price: "$95",
  },
  "dip-powder": {
    intro: "Dip powder nails delivered to your door \u2014 lightweight, durable, and no UV lamp needed. A healthier alternative to gel and acrylic with a beautiful, natural finish.",
    details: "Dip powder (SNS) involves dipping your nails into colored powder and sealing with activator for a hard, chip-resistant finish. It\u2019s lighter than acrylic, doesn\u2019t require UV curing like gel, and lasts 3\u20134 weeks. Our techs bring a full color selection and all supplies. Removal of previous dip sets available.",
    ideal: "Perfect for anyone who wants durability without the weight of acrylic or the UV exposure of gel. A favorite for natural nail lovers who want extra strength.",
    includes: ["Nail prep & cuticle care", "Base coat", "Dip powder application (2\u20133 layers)", "Activator & sealant", "Shaping & buff"],
    duration: "45\u201360 min",
    price: "$75",
  },

  // ── Women's Makeup ──
  "full-glam-makeup": {
    intro: "Camera-ready, event-level glam makeup delivered to your door by licensed makeup artists. Full coverage, contour, highlight, lashes, and lip \u2014 the works.",
    details: "Our makeup artists create full glam looks for weddings, galas, photo shoots, nights out, and any occasion where you want to look absolutely stunning. We use professional-grade products from brands like MAC, NARS, Charlotte Tilbury, and Make Up For Ever. Every application includes skin prep, primer, full-coverage foundation, concealer, contour, highlight, eye makeup, lashes (strip or individual), and lip.",
    ideal: "Essential for brides, events, photo shoots, content creation, or any time you want to feel like a celebrity.",
    includes: ["Skin prep & primer", "Foundation & concealer", "Contour & highlight", "Eye makeup & lashes", "Lip color & setting spray"],
    duration: "60\u201390 min",
    price: "$150",
  },
  "natural-everyday-makeup": {
    intro: "Enhanced, effortless beauty delivered to your door. A polished, natural makeup look that takes 30 minutes and makes you look like the best version of yourself.",
    details: "Our natural makeup service focuses on enhancing your features without the heavy, full-glam feel. Light coverage foundation or tinted moisturizer, subtle contour, soft eye makeup, natural brows, and a nude or soft lip. We also teach you the techniques we use so you can recreate the look at home.",
    ideal: "Perfect for professional headshots, everyday confidence, first dates, brunches, or anyone who wants to look polished without looking \u201cdone.\u201d",
    includes: ["Skin prep & moisturizer", "Light coverage base", "Soft eye & brow", "Natural lip", "Tips for recreating at home"],
    duration: "30\u201345 min",
    price: "$95",
  },
  "lash-application": {
    intro: "Professional strip lash and individual lash application delivered to your door. Instant drama, perfectly applied by a makeup artist who knows lashes.",
    details: "Our artists apply strip lashes or individual cluster lashes for a natural, dramatic, or wispy look \u2014 your choice. We bring a selection of lash styles and use professional lash adhesive for all-day (or all-night) hold. Lash application is also available as an add-on to any makeup service.",
    ideal: "Perfect as a standalone for events, or paired with any makeup service. Great for brides, prom, date night, or photo shoots.",
    includes: ["Lash style consultation", "Lash fitting & trimming", "Professional adhesive application", "Blending with natural lashes"],
    duration: "15\u201325 min",
    price: "$35",
  },

  // ── Women's Skin ──
  "express-facial": {
    intro: "A quick cleanse, tone, and glow-up facial delivered to your door. 30 minutes to refreshed, radiant skin without a spa appointment.",
    details: "Our express facial includes double cleansing, toner, a targeted serum, moisturizer, and SPF. It\u2019s designed for busy New Yorkers who want professional skincare without the time commitment of a full facial. Our estheticians assess your skin type and customize products accordingly.",
    ideal: "Perfect before an event, on your lunch break, or as a monthly maintenance ritual. Quick, effective, and refreshing.",
    includes: ["Double cleanse", "Toner", "Targeted serum", "Moisturizer", "SPF application"],
    duration: "30 min",
    price: "$75",
  },
  "deep-cleansing-facial": {
    intro: "A thorough deep cleansing facial with extractions, masks, and targeted treatment \u2014 delivered to your home by a licensed esthetician.",
    details: "This full facial includes double cleansing, exfoliation, steam, extractions (as needed), a custom mask, serum, moisturizer, and SPF. Our estheticians bring a portable steamer and professional-grade skincare products. We customize every step based on your skin type and concerns \u2014 acne, aging, hyperpigmentation, dryness, sensitivity.",
    ideal: "Ideal for anyone who wants a thorough, professional facial without the spa markup. Great monthly or quarterly as part of a skincare routine.",
    includes: ["Double cleanse & exfoliation", "Steam & extractions", "Custom mask", "Serum & moisturizer", "SPF"],
    duration: "60 min",
    price: "$120",
  },
  "microdermabrasion": {
    intro: "Professional microdermabrasion delivered to your door. Exfoliate dead skin cells, reduce fine lines, and reveal smoother, brighter skin \u2014 no spa visit required.",
    details: "Microdermabrasion uses a diamond-tip or crystal handpiece to gently remove the outer layer of dead skin cells, promoting cell turnover and collagen production. Our estheticians bring portable professional-grade devices and customize the intensity to your skin type and sensitivity. Followed by soothing serum, moisturizer, and SPF.",
    ideal: "Great for dull skin, uneven texture, fine lines, mild acne scarring, and hyperpigmentation. Recommended as a series of 4\u20136 treatments for best results.",
    includes: ["Skin assessment", "Cleansing & prep", "Microdermabrasion treatment", "Soothing serum & moisturizer", "SPF & aftercare instructions"],
    duration: "45 min",
    price: "$135",
  },
  "light-chemical-peel": {
    intro: "Gentle chemical peels for brighter, smoother skin \u2014 delivered to your home by a licensed esthetician. Resurface without the downtime of aggressive treatments.",
    details: "Our light chemical peels use glycolic acid, lactic acid, or salicylic acid to gently dissolve dead skin cells and promote cell renewal. The intensity is customized to your skin type, concerns, and tolerance. Mild tingling is normal; there\u2019s minimal to no downtime. Followed by neutralizer, calming serum, moisturizer, and SPF.",
    ideal: "Great for fine lines, dullness, mild acne, uneven tone, and texture. A gateway treatment for anyone new to professional skincare.",
    includes: ["Skin consultation", "Cleansing & prep", "Peel application", "Neutralizer", "Calming serum, moisturizer & SPF"],
    duration: "30\u201345 min",
    price: "$125",
  },

  // ── Women's Waxing ──
  "brow-wax-and-shape": {
    intro: "Clean, sculpted brows delivered to your door. Our waxing specialists shape your arches to frame your face using professional hard wax and precision techniques.",
    details: "We use professional hard wax (gentler on the skin than strip wax) to remove unwanted hair and create clean, defined brows. Every service includes a consultation on shape \u2014 we work with your natural arch and face shape to find the most flattering look. Includes tweezing for precision and soothing aloe post-wax.",
    ideal: "A quick, essential service that makes a huge difference. Perfect before events, photos, or as part of your regular grooming routine.",
    includes: ["Shape consultation", "Hard wax application", "Precision tweezing", "Soothing aloe", "Brow gel (optional)"],
    duration: "15\u201320 min",
    price: "$35",
  },
  "lip-and-chin-wax": {
    intro: "Quick, clean facial hair removal delivered to your door. Upper lip and chin waxing with professional hard wax for smooth, long-lasting results.",
    details: "Our specialists use hard wax for gentle, effective removal of upper lip and chin hair. Hard wax adheres to the hair, not the skin, making it less irritating than strip wax \u2014 especially on sensitive facial areas. Followed by soothing aloe or post-wax oil.",
    ideal: "Quick add-on to any service or standalone appointment. Results last 3\u20134 weeks.",
    includes: ["Hard wax application", "Removal", "Soothing post-wax care"],
    duration: "10\u201315 min",
    price: "$25",
  },
  "full-face-wax": {
    intro: "Complete facial waxing \u2014 brows, upper lip, chin, and sideburns \u2014 delivered to your door by a licensed waxing specialist.",
    details: "A full face wax covers all facial areas: brow shaping, upper lip, chin, jawline, and sideburns. We use professional hard wax throughout for maximum gentleness on the face. Includes post-wax soothing treatment to reduce redness.",
    ideal: "The all-in-one facial hair removal session. Great as a regular monthly service.",
    includes: ["Brow wax & shape", "Upper lip wax", "Chin wax", "Sideburn wax", "Soothing post-wax treatment"],
    duration: "25\u201335 min",
    price: "$65",
  },
  "bikini-brazilian-wax": {
    intro: "Professional bikini and Brazilian waxing delivered to your home. Clean lines or full removal \u2014 performed by experienced waxing specialists in the privacy and comfort of your own space.",
    details: "Choose from a bikini line cleanup (outside the panty line) or a full Brazilian (complete removal front to back). Our specialists use professional hard wax for minimum discomfort and maximum smoothness. We bring disposable supplies, sanitization products, and post-wax soothing oil. Your comfort and privacy are our top priority.",
    ideal: "Perfect before vacation, summer, or anytime. Having this done at home is far more comfortable and private than a salon.",
    includes: ["Area prep & cleanse", "Hard wax application", "Removal", "Post-wax soothing oil", "Aftercare instructions"],
    duration: "20\u201340 min",
    price: "$75\u2013$95",
  },
  "leg-wax": {
    intro: "Full leg and half leg waxing delivered to your door. Smooth, hair-free legs without the razor burn \u2014 performed by licensed waxing specialists.",
    details: "Choose between half leg (knee down) or full leg (ankle to hip) waxing. We use professional strip wax or hard wax depending on hair type and sensitivity. Results last 3\u20136 weeks \u2014 much longer than shaving, with less irritation and no stubble. We bring all supplies and disposables.",
    ideal: "Essential before summer, vacations, events, or for anyone who\u2019s tired of shaving every other day.",
    includes: ["Area prep", "Wax application", "Removal", "Post-wax soothing treatment", "Aftercare tips"],
    duration: "30\u201360 min",
    price: "$65\u2013$120",
  },
  "underarm-wax": {
    intro: "Quick, clean underarm waxing delivered to your door. Smooth results that last weeks longer than shaving, with less irritation.",
    details: "Our specialists use hard wax for gentle, effective underarm hair removal. Hard wax is ideal for the underarm area because it grips hair without pulling skin. Quick service, minimal discomfort, smooth results for 3\u20134 weeks.",
    ideal: "Perfect as a standalone or add-on to any other waxing service.",
    includes: ["Area prep", "Hard wax application", "Removal", "Soothing post-wax care"],
    duration: "10\u201315 min",
    price: "$30",
  },

  // ── Men's Hair ──
  "mens-haircut-and-style": {
    intro: "Classic or modern men\u2019s haircuts delivered to your door by licensed barbers. From textured crops to clean side parts, we cut to your style.",
    details: "Our barbers specialize in every men\u2019s style: textured crops, pompadours, side parts, undercuts, taper cuts, crew cuts, and more. Every cut includes a consultation, shampoo (if needed), precision cutting with clippers and shears, and a finished style with product. We bring professional clippers, guards, shears, and styling products.",
    ideal: "Perfect for guys who want a quality haircut without the barbershop wait. Great for busy professionals, dads, or anyone who values their time.",
    includes: ["Consultation", "Clipper & shear work", "Neckline & edge cleanup", "Styling with product"],
    duration: "30\u201345 min",
    price: "$75",
  },
  "fade-haircut": {
    intro: "Crisp fades \u2014 low, mid, or high \u2014 delivered to your door by barbers who specialize in precision fading. Blended to perfection, every time.",
    details: "A fade is all about the blend, and our barbers are masters of it. Whether you want a skin fade, shadow fade, drop fade, burst fade, or temp fade, we deliver barbershop-level precision in your living room. Every fade includes lineup, neck taper, and styling. We bring professional cordless clippers, multiple guards, and detailers.",
    ideal: "The most requested men\u2019s service in NYC. Perfect for maintaining a fresh look every 2\u20133 weeks without scheduling around a barbershop\u2019s walk-in list.",
    includes: ["Fade consultation (height & style)", "Clipper fade & blend", "Lineup & edge up", "Neck taper", "Styling"],
    duration: "30\u201345 min",
    price: "$99",
  },
  "line-up-edge-up": {
    intro: "Sharp hairline edges and lineups delivered to your door. Crisp, clean lines around the forehead, temples, and neckline.",
    details: "A line up (edge up) defines and sharpens the hairline using trimmers and a straight razor. Our barbers create razor-sharp lines around the forehead, temples, sideburns, and neckline. This is a quick maintenance service between haircuts to keep you looking fresh.",
    ideal: "The ultimate maintenance service. Get a lineup every week or two between full haircuts to always look sharp.",
    includes: ["Hairline shaping", "Temple & sideburn cleanup", "Neckline razor edge", "Styling"],
    duration: "15\u201320 min",
    price: "$45",
  },
  "buzz-cut": {
    intro: "Clean, even buzz cuts delivered to your door. Simple, low-maintenance, and always sharp.",
    details: "A buzz cut is the ultimate in simplicity \u2014 one guard length all over, or a slightly longer top with shorter sides. Our barbers ensure even coverage, clean edges, and a lineup. Quick, easy, and done.",
    ideal: "Perfect for guys who keep it simple. Low maintenance, always looks fresh, and takes under 20 minutes.",
    includes: ["Guard selection", "Full head buzz", "Lineup & edge cleanup", "Neck taper"],
    duration: "15\u201320 min",
    price: "$55",
  },

  // ── Men's Beard ──
  "beard-trim-and-shape": {
    intro: "Sculpted beard trims and shaping delivered to your door. Clean neckline, defined cheek line, and precision trimming by licensed barbers.",
    details: "Our barbers trim, shape, and sculpt your beard to your desired length and style. Includes neckline cleanup, cheek line definition, mustache trim, and blending with your hairline. We use professional trimmers, shears, and a straight razor for the cleanest lines.",
    ideal: "Essential maintenance for any man with a beard. Keep it looking intentional, not accidental.",
    includes: ["Length trim & shaping", "Neckline razor cleanup", "Cheek line definition", "Mustache trim", "Beard oil finish"],
    duration: "20\u201330 min",
    price: "$55",
  },
  "hot-towel-shave": {
    intro: "Old-school barbershop luxury delivered to your door. Hot towel prep, straight razor shave, and cold towel finish \u2014 the closest, smoothest shave possible.",
    details: "Our hot towel shave experience includes a hot towel wrap to open pores, pre-shave oil, lather application with a badger brush, a straight razor shave with the grain (and against, if desired), a cold towel to close pores, and aftershave balm. This is the kind of shave your grandfather got \u2014 except it comes to your living room.",
    ideal: "Perfect for special occasions, before events, or as a regular ritual for men who appreciate the finer things. Also great paired with a haircut.",
    includes: ["Hot towel prep", "Pre-shave oil", "Straight razor shave", "Cold towel", "Aftershave balm"],
    duration: "30\u201345 min",
    price: "$65",
  },
  "beard-oil-treatment": {
    intro: "Hydrating beard oil treatment delivered to your door. Soften, condition, and nourish your beard with professional-grade oils and a relaxing massage.",
    details: "Our beard oil treatment includes a warm towel wrap, application of premium beard oil blended for your beard type, a thorough beard and face massage, and combing for distribution. This treatment softens coarse hair, reduces itch, hydrates the skin underneath, and adds a healthy sheen.",
    ideal: "Great as an add-on to any beard service, or standalone for guys with dry, itchy, or coarse beards.",
    includes: ["Warm towel wrap", "Premium beard oil application", "Beard & face massage", "Combing & styling"],
    duration: "15\u201320 min",
    price: "$35",
  },

  // ── Men's Grooming ──
  "mens-brow-cleanup": {
    intro: "Clean, groomed brows for men \u2014 delivered to your door. Wax or tweeze for a natural, polished look without the unibrow.",
    details: "Our specialists clean up the brow area using wax, tweezers, or both \u2014 removing the unibrow, stray hairs, and any overgrowth while keeping a natural, masculine shape. This isn\u2019t about sculpting thin arches \u2014 it\u2019s about looking groomed without looking like you tried.",
    ideal: "A quick, subtle service that makes a big difference. Perfect before headshots, events, or as regular maintenance.",
    includes: ["Assessment & shaping", "Wax or tweeze", "Soothing post-treatment", "Natural finish"],
    duration: "10\u201315 min",
    price: "$25",
  },
  "ear-and-nose-wax": {
    intro: "Quick ear and nose hair removal delivered to your door. Clean, painless, and done in minutes.",
    details: "We use specialized hard wax designed for the nose and ear areas. A small amount of wax is applied, allowed to harden, and removed quickly \u2014 taking all visible hair with it. Far more effective and longer-lasting than trimming.",
    ideal: "Quick add-on to any men\u2019s grooming service. Takes 5 minutes, lasts 4\u20136 weeks.",
    includes: ["Nose wax", "Ear wax", "Post-wax soothing"],
    duration: "5\u201310 min",
    price: "$20",
  },
  "scalp-treatment": {
    intro: "Professional scalp treatment delivered to your door. Exfoliate, nourish, and rejuvenate your scalp for healthier hair growth.",
    details: "Our scalp treatment includes a thorough scalp analysis, exfoliation to remove product buildup and dead skin, a hydrating or stimulating scalp mask (based on your needs), and a relaxing scalp massage. We use professional products designed to promote healthy hair growth, reduce flaking, and soothe irritation.",
    ideal: "Great for guys dealing with dandruff, dry scalp, thinning, or product buildup. Also just an incredibly relaxing experience.",
    includes: ["Scalp analysis", "Exfoliation treatment", "Scalp mask application", "Scalp massage", "Rinse & style"],
    duration: "30\u201345 min",
    price: "$75",
  },
  "mens-manicure": {
    intro: "Clean, trimmed, buffed nails for men \u2014 delivered to your door. No polish required. Just well-groomed hands.",
    details: "Our men\u2019s manicure includes nail trimming and shaping, cuticle care, hand exfoliation, a brief hand massage, and buffing for a clean, natural shine. No polish unless you want it. Everything is sanitized between clients.",
    ideal: "A subtle but powerful grooming move. Great for professionals, before events, or as regular maintenance. Nobody needs to know \u2014 they\u2019ll just notice your hands look great.",
    includes: ["Nail trimming & shaping", "Cuticle care", "Hand exfoliation", "Massage", "Buffing"],
    duration: "25\u201335 min",
    price: "$45",
  },
  "mens-pedicure": {
    intro: "Men\u2019s pedicure delivered to your door. Soak, scrub, trim, and buff \u2014 because your feet deserve the same attention as the rest of you.",
    details: "Our men\u2019s pedicure includes a warm foot soak, callus removal (important for active guys and runners), nail trimming and shaping, cuticle care, foot scrub, and a foot massage. No polish unless you want it. We bring a portable foot basin and all sanitized tools.",
    ideal: "Perfect for athletes, runners, professionals on their feet all day, or anyone whose feet have been neglected. More common than you think \u2014 and it feels amazing.",
    includes: ["Foot soak", "Callus removal", "Nail trimming & cuticle care", "Exfoliation & massage", "Buffing"],
    duration: "35\u201350 min",
    price: "$65",
  },
  "back-wax": {
    intro: "Full back hair removal delivered to your door. Clean, smooth results by licensed waxing specialists in the privacy of your own home.",
    details: "Our specialists use professional strip wax or hard wax for full back hair removal, from the neckline to the waistline. We bring disposable sheets, sanitization supplies, and post-wax soothing products. Results last 4\u20136 weeks \u2014 far longer than shaving, with smoother results.",
    ideal: "Perfect before beach vacations, summer, pool parties, or just for comfort and confidence. Much easier than trying to do it yourself.",
    includes: ["Area prep", "Full back wax application", "Removal", "Post-wax soothing treatment", "Aftercare instructions"],
    duration: "30\u201345 min",
    price: "$85",
  },
};
